#!/bin/bash
PATH="/usr/bin:$PATH"

LD_LIBRARY_PATH="/usr/lib/$DEB_HOST_MULTIARCH:$LD_LIBRARY_PATH"

XDG_CONFIG_DIRS="/etc/xdg:${XDG_CONFIG_DIRS:-/etc/xdg}"
XDG_DATA_DIRS="/usr/share:${XDG_DATA_DIRS:-/usr/share/}"

QT_PLUGIN_PATH="/usr/lib/$DEB_HOST_MULTIARCH/qt5/plugins:$QT_PLUGIN_PATH"
QML2_IMPORT_PATH="/usr/lib/$DEB_HOST_MULTIARCH/qt5/qml:$QML2_IMPORT_PATH"

export PATH LD_LIBRARY_PATH XDG_CONFIG_DIRS XDG_DATA_DIRS QT_PLUGIN_PATH \
  QML2_IMPORT_PATH
